name: 'dbt_project'
version: '1.0'
config-version: 2

profile: 'dbt_project'

model-paths: ["models"]

models:
  dbt_project:
    staging:
      +schema: STAGING
      +materialized: view
    marts:
      +schema: MART
      +materialized: table
    analytics:
      +schema: ANALYTICS
      +materialized: table