CREATE DATABASE IF NOT EXISTS FRAUD_DETECTION_DB;

CREATE WAREHOUSE IF NOT EXISTS FRAUD_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

CREATE SCHEMA IF NOT EXISTS FRAUD_DETECTION_DB.RAW;
CREATE SCHEMA IF NOT EXISTS FRAUD_DETECTION_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS FRAUD_DETECTION_DB.MART;
CREATE SCHEMA IF NOT EXISTS FRAUD_DETECTION_DB.ANALYTICS;